apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-${id}
  namespace: kube-system
type: bootstrap.kubernetes.io/token
data:
  token-id: ${id}
  token-secret: ${secret}
  usage-bootstrap-authentication: true
  usage-bootstrap-signing: true
  auth-extra-groups: system:bootstrappers:kubelet:default-node-token
  description: "The default bootstrap token generated by 'terraform'"

