KUBELET_IMAGE_REPO="${kubelet_image_repo}"
KUBELET_IMAGE_TAG="${kubelet_image_tag}"
KUBECTL_IMAGE_REPO="${kubectl_image_repo}"
KUBECTL_IMAGE_TAG="${kubectl_image_tag}"
CFSSL_IMAGE_REPO="${cfssl_image_repo}"
CFSSL_IMAGE_TAG="${cfssl_image_tag}"
CLOUD_PROVIDER="${cloud_provider}"
NETWORK_PLUGIN="${network_plugin}"