apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: kube-controller-manager
spec:
  containers:
  - name: kube-controller-manager
    image: ${hyperkube_image}
    command:
    - ./hyperkube
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --configure-cloud-routes=false
    - --cluster-cidr=${cluster_cidr}
    - --kubeconfig=/etc/kubernetes/kubeconfig
    - --root-ca-file=${secret_path}/ca.crt
    - --service-account-private-key-file=${secret_path}/service-account.key
    - --cluster-signing-cert-file=${secret_path}/controller-manager.crt
    - --cluster-signing-key-file=${secret_path}/controller-manager.key
    - --leader-elect=true
    - --node-monitor-grace-period=${node_monitor_grace_period}
    - --pod-eviction-timeout=${pod_eviction_timeout}
    - --cloud-provider=${cloud_provider}
    ${cloud_provider_config_flag}
    volumeMounts:
    - name: secrets
      mountPath: ${secret_path}
      readOnly: true
    - name: ssl-host
      mountPath: /etc/ssl/certs
      readOnly: true
    - name: etc-kubernetes
      mountPath: /etc/kubernetes
  hostNetwork: true
  volumes:
  - name: etc-kubernetes
    hostPath:
      path: /etc/kubernetes
  - name: secrets
    hostPath:
      path: ${secret_path}
  - name: ssl-host
    hostPath:
      path: /usr/share/ca-certificates
