---
apiVersion: iamauthenticator.k8s.aws/v1alpha1
kind: IAMIdentityMapping
metadata:
  name: ${cluster_name}-admin
spec:
  arn: ${k8s_admin_iam_role}
  username: ${cluster_name}-admin
  groups:
  - system:masters           
                